use alloy_sol_types::sol;

// https://developers.circle.com/cctp/evm-smart-contracts
pub const MESSAGE_TRANSMITTER_ADDRESS: &str = "0x81D40F21F12A8F0E3252Bccb954D722d4c464B64";
pub const MESSAGE_TRANSMITTER_ADDRESS_TESTNET: &str = "0xE737e5cEBEEBa77EFE34D4aa090756590b1CE275";
pub const ARBITRUM_MESSAGE_TRANSMITTER_ADDRESS: &str = MESSAGE_TRANSMITTER_ADDRESS;
pub const ARBITRUM_SEPOLIA_MESSAGE_TRANSMITTER_ADDRESS: &str = MESSAGE_TRANSMITTER_ADDRESS_TESTNET;
pub const AVALANCHE_MESSAGE_TRANSMITTER_ADDRESS: &str = MESSAGE_TRANSMITTER_ADDRESS;
pub const BASE_MESSAGE_TRANSMITTER_ADDRESS: &str = MESSAGE_TRANSMITTER_ADDRESS;
pub const BASE_SEPOLIA_MESSAGE_TRANSMITTER_ADDRESS: &str = MESSAGE_TRANSMITTER_ADDRESS_TESTNET;
pub const ETHEREUM_MESSAGE_TRANSMITTER_ADDRESS: &str = MESSAGE_TRANSMITTER_ADDRESS;
pub const ETHEREUM_SEPOLIA_MESSAGE_TRANSMITTER_ADDRESS: &str = MESSAGE_TRANSMITTER_ADDRESS_TESTNET;
pub const OPTIMISM_MESSAGE_TRANSMITTER_ADDRESS: &str = MESSAGE_TRANSMITTER_ADDRESS;
pub const POLYGON_CCTP_MESSAGE_TRANSMITTER: &str = MESSAGE_TRANSMITTER_ADDRESS;
pub const UNICHAIN_CCTP_MESSAGE_TRANSMITTER: &str = MESSAGE_TRANSMITTER_ADDRESS;

sol!(
    #[allow(clippy::too_many_arguments)]
    #[allow(missing_docs)]
    #[sol(rpc)]
    MessageTransmitter,
    "abis/v2_message_transmitter.json"
);
